### ISSUE TITLE
[Help wanted] Observing doesn't work when observing the same signal twice in specific order 

### ISSUE THREAD

**Issue by Cedrick84** [ReactiveKit/ReactiveKit#153] opened 2017-06-14 20:45 UTC
Consider the following playground:

```swift
import UIKit
import ReactiveKit
import Bond
import PlaygroundSupport

class Test {
    let setString = SafePublishSubject<String>()
    let outputSubject = SafePublishSubject<Data>()
    let validMessageSubject = SafePublishSubject<String>()
    
    init() {
        let stringData = setString.map { $0.data(using: .utf8) }.ignoreNil()
        let stringValid = stringData.map { $0.count > 0 }
        
        stringValid // first
            .map { $0 ? "valid" : "not valid" }
            .bind(to: validMessageSubject)
        
        stringValid // second
            .filter { $0 }
            .with(latestFrom: stringData)
            .map { $0.1 }
            .bind(to: outputSubject)
    }
}


let test = Test()

test.validMessageSubject.observeNext { string in
    print(string)
}

test.outputSubject.observeNext { data in
    let s = String(data: data, encoding: .utf8)
    print(s)
}

test.setString.next("test string!")

PlaygroundPage.current.needsIndefiniteExecution = true
```

When a string is valid I want two actions to be invoked as seen above. One to print if its valid, the other the string when valid equals true.

Now in this example `outputSubject` is never invoked (the console now only prins `valid`). 
If I turn around the order of initialisation of the bindings to `stringValid` both are executed correctly.

```swift
...
        stringValid // new first (was second)
            .filter { $0 }
            .with(latestFrom: stringData)
            .map { $0.1 }
            .bind(to: outputSubject)
        
        stringValid // new second
            .map { $0 ? "valid" : "not valid" }
            .bind(to: validMessageSubject)
...
```

Now the console prints as I expect it
```
valid
Optional("test string!")
```

I would love to know why this behaviour is there so I can prevent this programming mistake in the future. Thanks so much

**Comment by srdanrasic** [comment] 2017-06-15 13:32
Hi @Cedrick84,

That's a very interesting issue. I think it's actually a bug - a very subtile one.

It has to do with `.with(latestFrom:)`. The "from" signal sends an event after "stringValid" signal sends its event so `.with(latestFrom:)` does not anything to combine with so no event is observed. 

Switching observers switches the oder of observer to which `setString` sends events so it works. The order is counter-intuitive in you example because it's actually random. Reason for that is that the subject keeps its observers in a dictionary and dictionary has undefined order.

I'll need to fix this by using order dictionary for subject observers. I'll probably do that over the weekend.

Sorry for the inconvenience.

**Comment by serieuxchat** [comment] 2017-06-15 13:36
Awesome that it could be addressed! I was diving into the same problem this morning and figured out more or less the same (by debugging the body of with(latestFrom:). But then thought that it was more of a 'feature' that had to be worked around. But if it gets fixed in the framework - even better! So thanks!

**Comment by srdanrasic** [comment] 2017-06-15 14:25
Yeah, maybe this is not a bug, but I feel like sending events in the order would provide more deterministic behaviour. Of course, this will not impact the normal behaviour of `with(latestFrom:)` that omits events when "from" signal sends nothing.

**Comment by serieuxchat** [comment] 2017-06-15 14:27
So, when they ARE sent in order, what would be the rule of thumb to use to get the signals triggered properly? Would we need to create bindings/observations in some specific order?

**Comment by srdanrasic** [comment] 2017-06-15 14:32
The change will mostly benefit `with(latestFrom:)` operator when feeding in the same signal (i.e. a signal derived from the same signal) as the one on which `with(latestFrom:)` was applied on. The order of bindings/observations should not be important.

**Comment by serieuxchat** [comment] 2017-07-07 12:14
Any updates on this?

**Comment by Cedrick84** [comment] 2017-08-07 11:36
@srdanrasic do you think you can find the time to push this change?

**Closed** 2017-08-09 18:36 UTC

**Comment by Cedrick84** [comment] 2017-08-09 18:45
Amazing, thanks!!!

**Comment by Cedrick84** [comment] 2017-08-15 08:00
One small request, can you update the Bond podspec so that the dependency on reactivekit is using this version?

Currently it's still on 3.5.3.
